package Vista;

import javax.swing.JButton;
import javax.swing.JDesktopPane;
import javax.swing.JToolBar;

/**
 *
 * @author Lenin
 */
public class VistaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VistaPrincipal
     */
    public VistaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopMain = new javax.swing.JDesktopPane();
        jToolBar1 = new javax.swing.JToolBar();
        btnCamion = new javax.swing.JButton();
        btnPersona = new javax.swing.JButton();
        btnProvincia = new javax.swing.JButton();
        btnViaje = new javax.swing.JButton();
        btnPaquete = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(desktopMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 820, 430));

        jToolBar1.setRollover(true);

        btnCamion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/camion.png"))); // NOI18N
        btnCamion.setToolTipText("Camiones");
        btnCamion.setFocusable(false);
        btnCamion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCamion.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnCamion);

        btnPersona.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/grupo-de-chat.png"))); // NOI18N
        btnPersona.setFocusable(false);
        btnPersona.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPersona.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnPersona);

        btnProvincia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/ecuador.png"))); // NOI18N
        btnProvincia.setToolTipText("Provincias");
        btnProvincia.setFocusable(false);
        btnProvincia.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnProvincia.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnProvincia);

        btnViaje.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/destino.png"))); // NOI18N
        btnViaje.setToolTipText("Viajes");
        btnViaje.setFocusable(false);
        btnViaje.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnViaje.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnViaje);

        btnPaquete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/caja.png"))); // NOI18N
        btnPaquete.setToolTipText("Paquetes");
        btnPaquete.setFocusable(false);
        btnPaquete.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPaquete.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnPaquete);

        getContentPane().add(jToolBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 25));

        jMenu1.setText("Personas");

        jMenuItem1.setText("Cliente");
        jMenuItem1.setToolTipText("Crud de cliente");
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Camionero");
        jMenuItem2.setToolTipText("Crud de camionero");
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JButton getBtnCamion() {
        return btnCamion;
    }

    public void setBtnCamion(JButton btnCamion) {
        this.btnCamion = btnCamion;
    }

    public JButton getBtnPaquete() {
        return btnPaquete;
    }

    public void setBtnPaquete(JButton btnPaquete) {
        this.btnPaquete = btnPaquete;
    }

    public JButton getBtnPersona() {
        return btnPersona;
    }

    public void setBtnPersona(JButton btnPersona) {
        this.btnPersona = btnPersona;
    }

    public JButton getBtnProvincia() {
        return btnProvincia;
    }

    public void setBtnProvincia(JButton btnProvincia) {
        this.btnProvincia = btnProvincia;
    }

    public JButton getBtnViaje() {
        return btnViaje;
    }

    public void setBtnViaje(JButton btnViaje) {
        this.btnViaje = btnViaje;
    }

    public JDesktopPane getjDesktopPane1() {
        return desktopMain;
    }

    public void setjDesktopPane1(JDesktopPane jDesktopPane1) {
        this.desktopMain = jDesktopPane1;
    }

    public JToolBar getjToolBar1() {
        return jToolBar1;
    }

    public void setjToolBar1(JToolBar jToolBar1) {
        this.jToolBar1 = jToolBar1;
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCamion;
    private javax.swing.JButton btnPaquete;
    private javax.swing.JButton btnPersona;
    private javax.swing.JButton btnProvincia;
    private javax.swing.JButton btnViaje;
    private javax.swing.JDesktopPane desktopMain;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
